### ISSUE TITLE
Unit tests fail due to missing IEndpointAddressProvider registration

### ISSUE THREAD

**Issue by liamstannard** [phatboyg/Demo-Registration#3]
Hi,

I believe we need to add a call to register an _IEndpointAddressProvider_ [somewhere around here in the PaymentActivity_Specs](https://github.com/phatboyg/Demo-Registration/blob/master/tests/Registration.Tests/PaymentActivity_Specs.cs#L79).  Without this, two of the unit tests fail with an InvalidOperationException.

My LOC to fix was simply:

`x.AddSingleton<IEndpointAddressProvider, RabbitMqEndpointAddressProvider>();`

Ran into this on a freshly cloned repo running the unit tests in Rider 2022.3

**Comment by phatboyg** [comment]
Thanks!
