### ISSUE TITLE
The 'log' variable can be reused

### ISSUE THREAD

**Issue by askrinnik** [phatboyg/Demo-Registration#4]
An anonymous object is created here to pass it as a `log `parameter
https://github.com/phatboyg/Demo-Registration/blob/master/src/Registration.Components/Activities/EventRegistrationActivity.cs#L64

As I understood the `log `variable, created in a line 43 can be reused. Right?

**Comment by phatboyg** [comment]
That isn't a log, it's variables. The activity in this case is execute-only.
